### ISSUE TITLE
possible to stack multiple slider panels on one side ?

### ISSUE THREAD

**Issue by EnriqueBE** [melistik/vaadin-sliderpanel#10]
Hello Martin, thanks for the great Vaadin addons ! I have a question about the SliderPanel: is it possible to stack multiple slider panels on one side ?

For example stack 3 different slider panels on the left side of the screen. Each with a distinct color and different content.
The tabs for the 3 panels should then appear next to each other.

An additional question: is it possible to tell the panels when to refresh their content?

Thx4the info!

**Comment by melistik** [comment]
Yes you can, combine Vertical- and Horizontal-Layout and place within each a SliderPanel.
Differnt colors you can handle by custom styleName and some css...
You can use a Listener to refresh on expand/collapse... 

Take a look in the demo-application this contains listeners and placing multiple slider to different postions of the screen.

**Comment by EnriqueBE** [comment]
Thanks Martin ! I am going to give it a try to learn the ropes.
