### ISSUE TITLE
Grid in SliderPanel

### ISSUE THREAD

**Issue by FoXTiSiTY** [melistik/vaadin-sliderpanel#11]
Hi,

I've created a com.vaadin.ui.Grid and added that to a VerticleLayout and the VerticleLayout to your SliderPanel. The grid is filled with a container datasource. 

If in the constructor we specify that it should be expanded by default, it all works perfectly fine but if we set it to not be expanded by default (which we prefer), and open up that slider, all the rows in the Grid have no more height. 

This one defaults to closed and opening it, displays like this:
![broken](https://cloud.githubusercontent.com/assets/12406751/7581567/ee03d1ec-f884-11e4-8670-bdacb31fa8e7.png)

This one defaults to open which shows everything perfectly fine:
![working](https://cloud.githubusercontent.com/assets/12406751/7581572/f5f85562-f884-11e4-9f74-421274be74c7.PNG)

**Comment by melistik** [comment]
Hi @FoXTiSiTY this issue we had already #5. seems to be a problem of the grid i was not able to find a solution. propably it's a problem of the grid-component itself. maybe we should create a ticket for vaadin

**Comment by melistik** [comment]
i don't know how to fix it...
