### ISSUE TITLE
sliderpanel with BrowserFrame

### ISSUE THREAD

**Issue by klemendrev** [melistik/vaadin-sliderpanel#12]
Hi!

I have a BrowserFrame with pdf content in it, and then right SliderPanel. This works perfectly in chrome and firefox but not in IE. Is there something I can do to fix this?

Here are some images of what i am talking about:
![chrome](https://cloud.githubusercontent.com/assets/240389/7913016/984c5524-086c-11e5-9b8b-ab3569ae0e2b.png)
![ie](https://cloud.githubusercontent.com/assets/240389/7913015/984bebac-086c-11e5-85f7-d93ee211d328.png)

Thanks,
Klemen

**Comment by melistik** [comment]
IE is not my favorite Browser and buyfixing this issue it hard for me because I don't habe IE on my Mac ;) Mabye you find a solution and post the css hack?

**Comment by klemendrev** [comment]
Thanks for reply. I found out that IE opens a Adobe plugin for viewing pdfs above everything. I use viewer JS instead and that solve my problem.
