### ISSUE TITLE
Effect of the expand different between the left and right slider

### ISSUE THREAD

**Issue by fredy2015** [melistik/vaadin-sliderpanel#13]
Hi,

Why the effect of the expand is different between the left and right slider? I mean when the right slider is expanded, all the content is moving. It's nice. When the left slider is expanded, the content looks static and it's revealed as and when the width is increasing.

Can we have the same effect in the left slider than we have on the right slider.
Thanks

**Comment by melistik** [comment]
yes you are right - i will try to solve it for the next release
