### ISSUE TITLE
setExpanded() doesn't always work

### ISSUE THREAD

**Issue by inahas** [melistik/vaadin-sliderpanel#17]
While I've had no issue using collapse() and expand(), setExpanded() doesn't seem to work all the time. In particular, I've noticed that if I manually expand the slider, setExpanded(false,..) doesn't collapse it back. However, if the slider was opened using setExpanded(true,...) then setExpanded(false,...) works.

**Comment by melistik** [comment]
Mhh have you maybe an example for me. I've checked the code and there is no difference between collapse/expand and setExpand...

**Comment by melistik** [comment]
without example
