### ISSUE TITLE
Grid wrapped with a HorizontalSplitPanel

### ISSUE THREAD

**Issue by initialflame** [melistik/vaadin-sliderpanel#18]
Hello,

we have got a Problem when we add a Grid to a Sliderpanel. Currently we have wrapped it with a HorizontalSplitPanel, but i think you can reproduce it also without wrapping it.

It seems that the grid checks for it's available space and has problems when the slider is collapsed initially...

Thank you for your help!

**Comment by melistik** [comment]
Hi,

i know this bug and it was also mentioned some issues before... I don't know how to solve it - seems that its something within the grid...

Best regards
Marten
