### ISSUE TITLE
Can't click on components inside the slider

### ISSUE THREAD

**Issue by slibert** [melistik/vaadin-sliderpanel#2]
Components inside the slider do not receive click events.
I made some testes with a simple button or with links.
Button is not event visually reacting to mouse click.

Simple code to reproduce issue ;
        VerticalLayout layout = new VerticalLayout();
        Button btn = new Button("TEST");
        layout.addComponent(btn);
        SliderPanel slider = new SliderPanel(layout, false, SliderMode.LEFT);
        slider.setCaption("Click Button plz");
        slider.setTabPosition(SliderTabPosition.MIDDLE);

**Comment by melistik** [comment]
1.0.5 has been released and demo has added some buttons. New version is solving your issue
