### ISSUE TITLE
Ivy version

### ISSUE THREAD

**Issue by aleksandaratanasov** [melistik/vaadin-sliderpanel#21]
Hi! It's more of a request then an issue really. Can you provide an `ivy.xml` along the `pom.xml` too? It would be more...beginner friendly especially since as far as I know in Eclipse the Vaadin plugin goes for Ivy where in NetBeans Maven is the first choice.

**Comment by melistik** [comment]
Hi, sorry for me late reply. 
Ivy is not vaadin's preferred dependency tool anymore. 
all examples, addons and so on are written in maven. 
Further more ivy should be able to read maven-poms.
