### ISSUE TITLE
SliderPanel improvement...

### ISSUE THREAD

**Issue by nazmul-prince** [melistik/vaadin-sliderpanel#24]
Attached a mock up view----
![slidingpanel](https://cloud.githubusercontent.com/assets/6926261/11114262/9cee6808-894d-11e5-9d8c-c4a3cec77701.png)

**Comment by melistik** [comment]
Hi, I didn't got your example and for me it doesn't make sense to place re right slider to the left corner of a window use LEFT one ;)
