### ISSUE TITLE
while content in sliderPanel is larger than the sliderPanel there's no scrollbar

### ISSUE THREAD

**Issue by olive009** [melistik/vaadin-sliderpanel#26]
while content in sliderPanel is larger than the sliderPanel there's no scrollbar

**Comment by melistik** [comment]
please post a code example! 
normally when you want to have a scrollbar you need to place a ScrollPanel as root of SliderPanel.

**Comment by olive009** [comment]
oh sorry, it seems my code's issue.  updating my panel ok now, thanks.
