### ISSUE TITLE
Auto-collapsing delay

### ISSUE THREAD

**Issue by slibert** [melistik/vaadin-sliderpanel#3]
Hello,

Would be really nice to have a setter that schedule an automatic collapse.
By now we can do that server-side with some code like :

```
        panel.addListener(new SliderPanelListener() {

            @Override
            public void onToggle(boolean expand) {

                if (expand)
                {
                    // Expanded, set a timer to collapse...
                    TimerTask timerTask = new TimerTask() {

                        @Override
                        public void run() {

                            logger.info("Collapsing !");
                            panel.collapse();

                        }
                    };
                    // running timer task as daemon thread
                    Timer timer = new Timer(true);
                    timer.schedule(timerTask, 4000);
                }
            }
        });
```

But it needs to set some push or pulling on.
Would be great if it happens client-side.

It could also be cool to make it collapse automatically when mouse leaves zone.

Regards

**Comment by melistik** [comment]
Hi silbert, I will try to implement such a function within the next release. 
My idea of the API would look like: 
- panel.scheduleCollapse(4000)
- panel.scheduleExpand(4000)
- panel.scheduleToggle(4000)
