### ISSUE TITLE
Vaadin SliderPanel not displaying properly

### ISSUE THREAD

**Issue by michaelruiz** [melistik/vaadin-sliderpanel#31]
I'm using the Vaadin add-on SliderPanel (https://vaadin.com/directory#!addon/sliderpanel) in my project and am having a very hard time making it go away and reappear on the correct view. When I load the application and log in, it correctly takes me to the correct class/page, 'Dashboard', with no SliderPanel. When I navigate to any other class/page which is supposed to re-display the SliderPanel, it does not appear as expected. In order for me to get it to show, I have to resize the window. Same thing happens when I resize the window then go back to the 'Dashboard' page...I have to resize the window and the SliderPanel tab goes away. How can I get the SliderPanel tab to update itself when changing views with the navigator?

In my UI I have @push() annotated above the main class.

```
@Push()
public class EvoltwebUI extends UI implements ClickListener {...}
```

Inside the class I have these annotations and servlet class:

```
@WebServlet(value = "/*", asyncSupported = true)
@VaadinServletConfiguration(productionMode = false, ui = EwebUI.class, widgetset = "com.e.eweb.widgetset.EwebWidgetset")

public static class Servlet extends VaadinServlet {
}
```

I've registered the views like this:

```

private void registerViews() {
        navigator.addView("dashboard", DashboardViewImpl.class);
        navigator.addView("groups", GroupsViewImpl.class);
        navigator.addView("research", ResearchViewImpl.class);
        navigator.addView("reporting", ReportsViewImpl.class);
        navigator.addView("execution", AdhocExecView.class);
        navigator.addView("tcreview", TestCaseReviewView.class);
        navigator.addView("toolbox", ToolboxView.class);
    }
```

The 'enter' method on each view/class looks like this:

```
@Override
public void enter(ViewChangeEvent event) {
    presenter.onViewEnter(event.getParameters());
    generateFields();
    ProgressPanel.setViewName("Test Case Review - Please load a group from the Test Group Explorer Slider Panel on the left.");
    UI.getTreeViewSlider().defaultTab();
}

```

I've tried using these, but I am having the same type of issue to where it will not come back if setVisible is false. :

```
leftTreeViewSlider.setVisible(true);
leftTreeViewSlider.setVisible(false);
```

I've also tried extending SliderPanel to access the actual size of the tab to shrink it, but when setting it back to the normal size I have to resize the window to get it back.

```
import org.vaadin.sliderpanel.SliderPanel;
import org.vaadin.sliderpanel.SliderPanelBuilder;    
import com.vaadin.ui.Component;

public class SliderPanelMod extends SliderPanel{

    public SliderPanelMod(SliderPanelBuilder builder) {
        super(builder);

    }

    public void resizeTab(int t) {
        this.getState().tabSize = t; 
    }

    public void defaultTab() {
        resizeTab(40);

    }

}

```

What would be causing this, or is there another workaround?

**Comment by melistik** [comment]
Hi, generally the SliderPanel work's fine in combination with Navigator...
I haven't tried it out with @Push annotation but ok we will see ;)

You described your problem quite detailed but for me one main information is missing.
How have you instantiated the SliderPanel and is it within one Navigator-Component or in the main layout?

Just to be clear: Instead of adding instances to the Navigator (new DashboardViewImpl()), you've added classes this means that each time you navigate to one particular nav it will get reinitialized each time you click on it. See Api-Doc of Navigator 

> "A new view instance is created every time a view is requested."  

Maybe this lead's to your problem...

**Comment by melistik** [comment]
no feedback...
