### ISSUE TITLE
Unable to click are when slider already hide

### ISSUE THREAD

**Issue by ndwijaya** [melistik/vaadin-sliderpanel#4]
on version 1.0.4

![sliderpanel-wrong-sample](https://cloud.githubusercontent.com/assets/11312261/7109041/219ef508-e1c0-11e4-8ae2-b5ed43418714.png)

**Comment by melistik** [comment]
Hi, could you please check version 1.0.5 that should solve propably the issue. In the demo with the latest version I'm able to click the mainButton... http://non-rocket-science.jelastic.servint.net/vaadin-sliderpanel/

**Comment by ndwijaya** [comment]
Thanks, is working well on 1.0.5.
