### ISSUE TITLE
component overflowing to right

### ISSUE THREAD

**Issue by lipodido** [melistik/vaadin-sliderpanel#7]
I have bottom sliderpanel That contains horizontallayout
the horizontallayout contains:
Label ()  (with expandratio 1)
savebutton 
cancelbutton
After changing theme the elements overflow to right and don't show up until collapsing and expanding again.

![slider](https://cloud.githubusercontent.com/assets/7419872/7315973/c9261620-ea72-11e4-856f-1ed751363cfb.JPG)

**Comment by melistik** [comment]
Hi lipodido,
i've tried to reproduce your issue but wilth no success:

when I change my demo:

``` java
private VerticalLayout dummyContent(final String title, final int length) {
    String text = "";
    for (int x = 0; x <= length; x++) {
        text += LOREM_IPSUM + " ";
    }
    Label htmlDummy = new Label(String.format("<h3>%s</h3>%s", title, text.trim()), ContentMode.HTML);
    VerticalLayout component = new VerticalLayout(htmlDummy);
    component.setExpandRatio(htmlDummy, 1);

    HorizontalLayout hLayout = new HorizontalLayout();
    hLayout.setWidth(100, Unit.PERCENTAGE);
    Label spacingLabel = new Label("");
    hLayout.addComponent(spacingLabel);
    hLayout.setExpandRatio(spacingLabel, 1);
    hLayout.addComponent(new Button(title, new Button.ClickListener() {
        @Override
        public void buttonClick(final ClickEvent event) {
            Notification.show("clicked: " + title, Type.HUMANIZED_MESSAGE);
        }
    }));
    component.addComponent(hLayout);
    component.setMargin(true);
    component.setSpacing(true);
    return component;
}
```

the result looks as expected
![layout-issues](https://cloud.githubusercontent.com/assets/1936030/7332608/7cbb5eb4-eb47-11e4-8cc9-dce3a381e12f.jpg)

when you still have a problem please post your example code

**Comment by lipodido** [comment]
thanks for your reply , but the difference is that i have a side menu panel  (the famous valo side menu panel with menu item ) and when i remove it everything goes fine.

**Comment by lipodido** [comment]
I just download the valo demo from https://github.com/vaadin/valo-demo
I add the following view (and you dummyContent methode) 
after clicking "change theme" everything overflow to right

```
public class MiscTest extends VerticalLayout implements View {
    public MiscTest() {
        setMargin(true);
        setSpacing(true);
        //Add button to change theme
        addComponent(new Button("Change theme", new Button.ClickListener() {
            @Override
            public void buttonClick(ClickEvent event) {
                // TODO Auto-generated method stub
                if (UI.getCurrent().getTheme().equals("tests-valo"))
                    UI.getCurrent().setTheme("tests-valo-facebook");
                else
                    UI.getCurrent().setTheme("tests-valo");
            }
        }));
        //add Some Main Content
        addComponent(dummyContent("Main Content", 10));
        //add Slider
        SliderPanel slider = new SliderPanel(dummyContent("Details", 5),
                false, SliderMode.BOTTOM);
        addComponent(slider);
    }
    @Override
    public void enter(ViewChangeEvent event) {
    }
}
```

before click

![slider_before_click](https://cloud.githubusercontent.com/assets/7419872/7333315/3c710876-eb6b-11e4-928a-e69c87510b96.png)

after click

![slider_after_click](https://cloud.githubusercontent.com/assets/7419872/7333329/b27e9e34-eb6b-11e4-91c6-d6414a632914.png)

**Comment by melistik** [comment]
Hi it's not a problem of the slider itself. The layout around the slider leads to the problem...
The expandRatio is not calculated correctly that's why not only the slider itself floats out the browser...

![reason-for-problem](https://cloud.githubusercontent.com/assets/1936030/7334772/41e136fa-eb9d-11e4-9906-8ecc2b3a7ccf.jpg)

**Comment by lipodido** [comment]
any workaround ? thank you for taking time analyzing this and for this great addon
