### ISSUE TITLE
Table in SliderPanel

### ISSUE THREAD

**Issue by khannar** [melistik/vaadin-sliderpanel#8]
I am using the left slider panel. The content of the panel are some text fields and a table populated with data. The table is redrawn whenever the panel is expanded. The text fields are not. Data entered in the text fields is retained on collapse and next expand. Does the table behave in a different way or am I doing something wrong.

Thanks for providing a great add-on.

**Comment by melistik** [comment]
Normally I don't give the content of the SliderPanel a hint to redraw. I will check it and give you feedback...

**Comment by melistik** [comment]
there is no trigger on the content to redraw itself - so propably the table does it by it's own because of the changes of the visibility or width... Maybe I can recheck when you post your example code...
